### ISSUE TITLE
UI Concepts

### ISSUE THREAD

**Issue by adamnew123456** [markjm/426project#1]
We can use this as a place to plan out how we want the interface to look and function.

**Comment by adamnew123456** [comment]
A couple of initial thoughts:
- A "basic view" which is just a table, maybe with some search functions
- Different categorizations on the basic view
  - Status (passed, in-progress, dead)
  - Cost (cost vs. no-cost)

**Comment by markjm** [comment]
Check out the basic site i put up. Each of those panels will be created and updated when the cob introduces a new cost estimate document. The learn more page could be an "interactive" (to the degree we can make it) example. The sidebars will change.

**Comment by adamnew123456** [comment]
I've put a bit of sample data into the skeleton to see what it looks like: http://htmlpreview.github.io/?https://github.com/adamnew123456/426project/blob/sample-data/index.html

It includes the bill name, revenue and spending estimates.

**Comment by adamnew123456** [comment]
Worked in a couple of other changes:
- Added "CBO Simplifier" as the name of the site. It was the first thing I came up with, but we can rework it without much trouble.
- Removed some unused page elements.
- Added a blank about page
- Extracted a template for creating new pages: https://htmlpreview.github.io/?https://raw.githubusercontent.com/adamnew123456/426project/sample-data/bootstrap-template.html. All it includes is the navbar and the main body, but it's a common place for all the CSS/JS includes Bootstrap needs.

**Comment by adamnew123456** [comment]
Added some text to the about page.

**Comment by adamnew123456** [comment]
Pushed a very rough version of the contribution page, and added some links to the cost estimates themselves on the main page.

**Comment by adamnew123456** [comment]
Pushed the current version to [http://cs.unc.edu/~camarche/426/](http://cs.unc.edu/~camarche/426/) to make it a bit more comfortable to view.

**Comment by markjm** [comment]
I'm still looking into the possibility of automating the data collection from a pdf. Check out pdftables and/or tabula

**Comment by adamnew123456** [comment]
Looking at the PDFs, [not all of them are quite so regular](https://www.cbo.gov/sites/default/files/114th-congress-2015-2016/costestimate/hr5428.pdf).

I've looked into scraping the data from the web page via BeautifulSoup and picking out some potential matches via regex. This seems to be fairly promising - I've cobbled together the following regex from a couple of examples:

```
(\w+\W){0,10}(\$[0-9]+(\.[0-9]+)?)\W(billion|million|thousand)+\Wover\Wthe\W[0-9]+-[0-9]+\Wperiod
```

It's pretty gnarly, and we'll still probably need some kind of human review, but it does a good job of suggesting things that might be useful. For example, when pasting the [cost estimate of S. 2138](https://www.cbo.gov/publication/52134) in to [this regex tester](https://regex101.com/), it makes the following suggestions:
- `2138 would cost the SBA and other federal agencies $11 million over the 2017-2021 period`
- `CBO estimates that the additional work would cost $5 million over the 2017-2021 period`
- `100,000 a year or a total of about $6 million over the 2017-2021 period`

**Comment by adamnew123456** [comment]
Also, a quick UI for the explore pane is up.

**Comment by adamnew123456** [comment]
Do we want to put everything on the UI mockups as it is now, or are there any changes we need to make first? It probably isn't very important to get it into _final_ form, but any major changes should probably get in if we can.

I'm setting up the mockup pages in my directory with what we've got now.

**Comment by markjm** [comment]
I think its good as is. I will try and go through it today and clean some things up

**Comment by adamnew123456** [comment]
Okay, I'll go ahead and merge what I've got into the main repo so you can work with it. You'll want to update your local copy before you do anything.

**Comment by markjm** [comment]
I like how it looks currently. The contribute page needs work, but I think there may be a better way to go about that. Is this currently up on your webspace, or should i put it up?

**Comment by adamnew123456** [comment]
Yeah, I've got a [bit up for it](http://www.cs.unc.edu/Courses/comp426-f16/users/camarche/final_project_milestones/), I might add a little bit in a bit.
