### ISSUE TITLE
uncDatabase Design & Server API

### ISSUE THREAD

**Issue by adamnew123456** [markjm/426project#3]
Related open questions:

- What kinds of information about bills do we want for search? Draft list from the CBO's site:
    - Publish date
    - The Congress under which the bill was proposed (dependent upon publish date)
    - Committee
    - Net effect on the budget
- Will human review for summaries be required? (Will have to have some way of identifying *pending* vs *finished* summaries)

All of the search fields are available on the bill's page itself, in a fairly scrape-friendly form (except the Congress, but that's easy to calculate since each Congress seats at the same time). I'll augment some of the scraping scripts on my end to try to capture this information.

**Comment by markjm** [comment]
RELATION Bill
int id
link or copy of pdf report
date published
string summary
string $+
string $-
----possible additions---
int agree
int disagree (for a voting system, if we want to do that)

I don't know that we'd need the congress, because the purpose is generally to look at newly introduced bills, but I'm open to it, if so: another table

RELATION Congress
int id
daterange session
string/in Congress (don't know how they are identified)

**Comment by adamnew123456** [comment]
How do we want to separate out the time-ranges given by CBO budget cost/revenue estimates? A lot of them give 5 _and_ 10 year figures - do we want overall cost/revenue as just two figures (and if so, how do we represent multiple costs over different timespans?)? Or do we want to separate it out into something like:

| Type (C/R) | Amount | Timespan (Years) |
| --- | --- | --- |
| COST | 15000000 | 10 |
| REVENUE | 5000000 | 5 |

Just to clarify - the bill's summary is its title, right?

Don't worry about Congresses - you can easily figure out the Congress number from the publish date, so there's no reason to keep that information in the database:

```
effective_year = PUB_DATE.year
if PUB_DATE.month == 'January' and PUB_DATE.day < 3:
    effective_year -= 1 # Congress seats on Jan. 3

return floor((effective_year - 1789) / 2) + 1
```

**Comment by markjm** [comment]
We should have a bill title and a separate couple sentence summary about the bill (like the first paragraph of the summaries on the website).

For the timespans, we can do what you proposed, or just store them as strings with the information in it. We likely won't be doing any sort of calculations with the numbers, so it shouldn't matter too much.

**Comment by adamnew123456** [comment]
As far as server API, here are my thoughts on the endpoints:

- `GET /bills` should produce the IDs of all of the bills as JSON, along with all of
  their information:

        {
            ...,
            3: {'title': 'Military Residency Choice Act',
                'code': 'H.R. 5248',
                'summary': '...',
                'committee': "House Committee On Veterans' Affairs",
                'cbo_url': '...',
                'pdf_url': '...',
                'published': '2016-10-24',
                'financial': []
            },
            4: {'title': 'Veterans First Act', 
                'code': 'S. 2921',
                'summary': '...',
                'committee': '...',
                'published': '...',
                'cbo_url': '...',
                'pdf_url': '...',
                'financial': [{'timespan': 10, 'amount': 3900000000},
                              {'timespan': 5, 'amount': -3500000000}]
            },
            'next': '/api.php/bills?start=5'
        }
        
- `GET /bills?before=<TIMESTAMP>&after=<TIMESTAMP>&committee=<NAME>`
  allows for search queries to pick out bills which are before/after a certain
  date (represented by the Unix timestamp), or the committee name.

**EDIT** Both of these have pagination, to avoid having to pull the entire database and send it to the client every time they run a search or look at the homepage. It might be `null` if there is no page after this page.

**EDIT** Congress isn't a part of the API anymore, since the frontend could calculate this and update the bounds on the user's provided before and after dates appropriately (for example, if the `before` is the year 2010, but the user wants the 114th Congress, the year should be set to 2014 instead).

**EDIT** Add committee and publish date into.
  
I might add something for contributions, if they can't be done automatically. I
have a couple thoughts on this, but it depends upon what we'll need from users.

**Comment by adamnew123456** [comment]
Pushed the current version of the backend; see [my backend branch](https://github.com/adamnew123456/426project/tree/backend). I haven't tested any of the APIs yet, but there is a script that generates data for the DB which is the same as what we've got on the filler-data homepage.

**Comment by adamnew123456** [comment]
Got [the backend](https://github.com/adamnew123456/426project/tree/backend) working - it correctly does query processing, pagination, and returns the results in the form specified above (committee and publish information included).

**Comment by markjm** [comment]
To clarify:

GET /bills?start=<INTEGER>&before=<UNIX-TIMESTAMP>&after=<UNIX-TIMESTAMP>&comittee=<NAME>

What is START referring to?

**Comment by adamnew123456** [comment]
From the point of view of the frontend code, `start` is a purely opaque thing - you should only pass it when you do AJAX on the `next` URL in the JSON you get back, otherwise you can ignore it.

Implementation-wise, it's the ID of the last object that you've looked at, so that the database can skip those when generating the next page of results.

**Comment by markjm** [comment]
Are you free to meet after class tomorrow quickly? I'm not sure whats going wrong when trying to communicate with the backend.

**Comment by markjm** [comment]
Also, just a though:

Do we want to care about the timespan? Focusing on the net impact to the budget, the time those funds are appropriated doesn't matter.

**Comment by adamnew123456** [comment]
So, I haven't gotten the backend running on classroom.cs.unc.edu yet, the testing was entirely on a VM I ran on my machine. I'll probably get it running sometime tonight, and post the URL to the PHP script, and run a couple of basic tests with it to ensure that it runs. I'm good to meet if there are still issues when I get it running.

As for timespan: my gut says that it's important in a way that one of the bills in the sample data exemplifies - you could have $5 billion in revenue vs $5 billion in expendiatures, but the revenues over 10 yrs. and expendiatures over 5 yrs. The summarized net effect is somewhat misleading, in that the net effect is in the red until the full revenues accrue at year 10, but the summary would show that the bill has no net impact.

Maybe I'm overthinking it.

**Comment by adamnew123456** [comment]
Okay, I've put it up the PHP script at http://wwwp.cs.unc.edu/~camarche/426/api.php - as far as I can tell, it's digesting requests properly and returning sane output. I had to rework a couple of things to account for the department's PHP setup, but it should be good to go.

**Comment by markjm** [comment]
Hey,

Right now, the last json object with data is sent with a next url the just gives back a blank page with just "next": null.

Is there any way for that null to be pushed to the previous son file?

**Comment by adamnew123456** [comment]
It should be - I'll look into it.

**Comment by adamnew123456** [comment]
It's up and running now, and is operating correctly.

**Comment by adamnew123456** [comment]
Also, is there anything that might help with regards to bill ordering? I know that you can do that in the JS, but if you want to work that into the backend (something like a `"bill_ids": ["5", "3", "4"]` that gives the bill IDs in reverse-chronological order) it's a very minor addition on my part.

**Comment by markjm** [comment]
The big thing would be having orderings by date, committee, and net cost.

Those are ones that need to be sorted server side (because the json is sent page at a time, and I'd need all the pages to correctly sort)

**Comment by adamnew123456** [comment]
I'll be modifying the API a bit to compensate:

1. The bills will be part of a JSON list called "bills", instead of embedded in the outer object
2. `GET` will have a **mandatory** `order`, which can be either `date`, `committee`, or `net` along with `+asc` or `+desc`. For example, `GET /bills?order=date+desc`. (Note that `net+desc` will start with the net positive bills and `net+asc` will start with the net negative bills) 

The net result should be:

    GET /bills?order=date+desc
    
      {
        'bills': [
          {'title': 'Military Residency Choice Act',
              'code': 'H.R. 5248',
              'summary': '...',
              'committee': "House Committee On Veterans' Affairs",
              'cbo_url': '...',
              'pdf_url': '...',
              'published': '2016-10-24',
              'financial': []
          },
          {'title': 'Veterans First Act', 
            'code': 'S. 2921',
            'summary': '...',
            'committee': '...',
            'published': '2016-10-22',
            'cbo_url': '...',
            'pdf_url': '...',
            'financial': [{'timespan': 10, 'amount': 3900000000},
                          {'timespan': 5, 'amount': -3500000000}]
          }
        ]
        'next': '/api.php/bills?start=2&order=date+desc'
      }

**Comment by adamnew123456** [comment]
Ordering up and running.
